# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: Go

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.22'

    - name: Build
      run: make b
    - name: SSH
      run: |
        mkdir -p ~/.ssh 
        echo $'Host *\n    StrictHostKeyChecking no' > ~/.ssh/config
        echo "${{ secrets.SSH_PUB }}" >> ~/.ssh/id_rsa.pub
    - uses: webfactory/ssh-agent@v0.9.0
      with:
        ssh-private-key: ${{ secrets.SSH_PRIV }}
    - name: Deploy
      run: sftp root@8.220.204.169:/root/apps/memo/ <<< $'put -r *'
    - name: Deploy2
      run: ssh root@8.220.204.169 "cd /root/apps/memo && kill $(ps aux | grep 'memo' | awk '{print $2}') & ./bin/memo &"
